### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by HJava** [shinima/battle-city#7]
I get an error when I pass the 1st mission and play the 2rd mission:
通过了第一关以后跳转到第二关，然后出现了下面的错误：
```
uncaught at s at s 
 at f 
 at E 
 at E 
 at d 
 at _ 
 at u 
 TypeError: Cannot destructure property `active` of 'undefined' or 'null'.
    at t.playerTank (http://shinima.pw/battle-city/main-c3d36b.js:14:80639)
    at http://shinima.pw/battle-city/main-c3d36b.js:14:125601
    at L (http://shinima.pw/battle-city/main-c3d36b.js:14:125654)
    at D (http://shinima.pw/battle-city/main-c3d36b.js:14:126447)
    at M (http://shinima.pw/battle-city/main-c3d36b.js:14:122393)
    at c (http://shinima.pw/battle-city/main-c3d36b.js:14:126208)
    at http://shinima.pw/battle-city/main-c3d36b.js:14:125631
    at L (http://shinima.pw/battle-city/main-c3d36b.js:14:125654)
    at D (http://shinima.pw/battle-city/main-c3d36b.js:14:126447)
    at M (http://shinima.pw/battle-city/main-c3d36b.js:14:122393)
X @ main-c3d36b.js:1
```

![image](https://user-images.githubusercontent.com/3412268/38631637-e180d8a6-3dec-11e8-9a52-464836846338.png)

**Comment by shinima** [comment]
@HJava 多谢反馈，看起来和 #6 的情况是一样的。
